language: node_js

node_js:
  - "0.10"

before_install:
  - gem install scss-lint
  - npm install -g npm

before_script:
  - npm install -g gulp

script:
  - gulp tests

env:
  global:
    - secure: Vd/CeUcWVUsgejibIiq8PQT1xfK7SYRdWSdol6ymGb2LVI5ckm4rOGm+FBdbKip43oqgpkM7sLqBzSUTVTsGdea87tiKJKpp4AXaKTgkzG9LzY6eX67fnWvG2WOfTdrLIeUwjY/HVlAQC8ymaZ09Nj6Rhb7dKoziEW7+uqGjGjo=
    - secure: gRrsTzeBs+2N7pi95FQ4lhhAzqXlwsVR8fBwPfYVY6s+kqFzyh7KeFuy2uH5JiS3MPP+XIihT9r6jf5rmmhoLIGTEpos3HZYGkaSEPSPybvNVdVoTnMzaNlrMdCLgw1/S15K1luhyR6PqvfVxoD+PTUNeT0s/YUuxMpsuvMgGtE=
